name: weather
version: '0.1'
summary: Fetches Weather Information From OpenWeather
description: Weather Information From OpenWeather

grade: stable
confinement: strict

parts:
  weather-part:
    plugin: python
    source: .

apps:
 weather:
      command: weather
      plugs:
       - home
       - network 
